version: '3'

services:
  redis:
    image: redis:6.2.4
    ports:
      - 6379:6379
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shop_development
  jaeger:
    image: jaegertracing/all-in-one:1.23.0
    ports:
      - 6832:6832/udp
      - 16686:16686
