version: '3'

services:
  redis:
    image: redis:6.2.4
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    # 如果需要mysql持久化，则打开注释，会保存数据，重启镜像不会丢失
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shop_development
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -uroot -ppassword']
      interval: 10s
      timeout: 5s
      retries: 3
  jaeger:
    image: jaegertracing/all-in-one:1.23.0
    ports:
      - 6832:6832/udp
      - 16686:16686
